CREATE TABLE IF NOT EXISTS "actors" (
  "id" SERIAL PRIMARY KEY,
  "name" VARCHAR(100),
  "birthdate" TIMESTAMP,
  "bio" VARCHAR(200),
  "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
